<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HoNRebornRU.Updater</AssemblyName>
    <RootNamespace>HoNRebornRu.Updater</RootNamespace>
    <Version>1.0.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\HoNRebornRu.Launcher\Assets\app-icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
