#!/usr/bin/env python3
"""Generate compact native-HUD benchmark data from HoN Plus aggregates."""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path


METRICS = ("cs", "creepDenies", "kills", "deaths", "assists", "level")
POINTS = ("min", "p10", "p25", "p50", "p75", "p90", "max")


def lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def number(value: object) -> str:
    if value is None:
        return "0"
    numeric = float(value)
    if numeric.is_integer():
        return str(int(numeric))
    return f"{numeric:.3f}".rstrip("0").rstrip(".")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--benchmarks", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rows = json.loads(args.benchmarks.resolve().read_text(encoding="utf-8"))
    with urllib.request.urlopen("https://gamedata.juvio.com/entities/heroes", timeout=30) as response:
        heroes = json.load(response).get("heroes", [])

    hero_names: dict[str, int] = {}
    for hero in heroes:
        hero_id = int(hero.get("id") or 0)
        if not hero_id:
            continue
        for key in (hero.get("name"), hero.get("translatedName")):
            if key:
                hero_names[str(key).strip().lower()] = hero_id

    eligible = [
        row for row in rows
        if row.get("map") == "ForestsOfCaldavar"
        and int(row.get("roleIndex") or 0) in range(1, 8)
        and int(row.get("minute") or 0) >= 5
    ]
    grouped: dict[int, dict[int, list[dict]]] = {}
    for row in eligible:
        grouped.setdefault(int(row["heroId"]), {}).setdefault(int(row["roleIndex"]), []).append(row)

    lines = ["-- Generated by tools/generate_honplus_live_data.py; do not edit.", "HoNPlusLiveData = {", "  heroes = {"]
    for name, hero_id in sorted(hero_names.items()):
        lines.append(f"    [{lua_string(name)}]={hero_id},")
    lines.extend(["  },", "  benchmarks = {"])
    groups = 0
    for hero_id, roles in sorted(grouped.items()):
        lines.append(f"    [{hero_id}]={{")
        for role, role_rows in sorted(roles.items()):
            lines.append(f"      [{role}]={{")
            for row in sorted(role_rows, key=lambda item: int(item["minute"])):
                fields = [f"n={int(row['sampleCount'])}"]
                metrics = row.get("metrics", {})
                for metric in METRICS:
                    values = metrics.get(metric)
                    if not values:
                        continue
                    fields.append(metric + "={" + ",".join(number(values.get(point)) for point in POINTS) + "}")
                lines.append(f"        [{int(row['minute'])}]={{" + ",".join(fields) + "},")
                groups += 1
            lines.append("      },")
        lines.append("    },")
    lines.extend(["  }", "}", ""])
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(json.dumps({"output": str(output), "groups": groups, "hero_names": len(hero_names), "bytes": output.stat().st_size}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
