#!/usr/bin/env python3
"""Generate compact native-HUD benchmark data from HoN Plus aggregates."""

from __future__ import annotations

import argparse
import json
import urllib.request
from itertools import islice
from pathlib import Path


METRICS = ("cs", "creepDenies", "kills", "deaths", "assists", "level")
POINTS = ("min", "p10", "p25", "p50", "p75", "p90", "max")


def lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def number(value: object) -> str:
    if value is None:
        return "0"
    numeric = float(value)
    if numeric.is_integer():
        return str(int(numeric))
    return f"{numeric:.3f}".rstrip("0").rstrip(".")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--benchmarks", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--chunks", type=int, default=32)
    args = parser.parse_args()
    rows = json.loads(args.benchmarks.resolve().read_text(encoding="utf-8"))
    with urllib.request.urlopen("https://gamedata.juvio.com/entities/heroes", timeout=30) as response:
        heroes = json.load(response).get("heroes", [])

    hero_names: dict[str, int] = {}
    for hero in heroes:
        hero_id = int(hero.get("id") or 0)
        if not hero_id:
            continue
        for key in (hero.get("name"), hero.get("translatedName")):
            if key:
                hero_names[str(key).strip().lower()] = hero_id

    eligible = [
        row for row in rows
        if row.get("map") == "ForestsOfCaldavar"
        and int(row.get("roleIndex") or 0) in range(1, 8)
        and int(row.get("minute") or 0) >= 5
    ]
    grouped: dict[int, dict[int, list[dict]]] = {}
    for row in eligible:
        grouped.setdefault(int(row["heroId"]), {}).setdefault(int(row["roleIndex"]), []).append(row)

    lines = ["-- Generated by tools/generate_honplus_live_data.py; do not edit.", "HoNPlusLiveData = {", "  heroes = {"]
    for name, hero_id in sorted(hero_names.items()):
        lines.append(f"    [{lua_string(name)}]={hero_id},")
    lines.extend(["  },", "  benchmarks = {}", "}", ""])
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    for stale in output.parent.glob(output.stem + "_*.lua"):
        stale.unlink()

    hero_items = list(sorted(grouped.items()))
    chunk_size = max(1, (len(hero_items) + max(1, args.chunks) - 1) // max(1, args.chunks))
    groups = 0
    chunk_count = 0
    iterator = iter(hero_items)
    while batch := list(islice(iterator, chunk_size)):
        chunk_count += 1
        chunk_lines = ["-- Generated HoN Plus benchmark chunk; do not edit.", "local B=HoNPlusLiveData.benchmarks"]
        for hero_id, roles in batch:
            chunk_lines.append(f"B[{hero_id}]={{")
            for role, role_rows in sorted(roles.items()):
                chunk_lines.append(f"  [{role}]={{")
                for row in sorted(role_rows, key=lambda item: int(item["minute"])):
                    fields = [f"n={int(row['sampleCount'])}"]
                    metrics = row.get("metrics", {})
                    for metric in METRICS:
                        values = metrics.get(metric)
                        if not values:
                            continue
                        fields.append(metric + "={" + ",".join(number(values.get(point)) for point in POINTS) + "}")
                    chunk_lines.append(f"    [{int(row['minute'])}]={{" + ",".join(fields) + "},")
                    groups += 1
                chunk_lines.append("  },")
            chunk_lines.append("}")
        chunk_path = output.with_name(f"{output.stem}_{chunk_count:02d}.lua")
        chunk_path.write_text("\n".join(chunk_lines) + "\n", encoding="utf-8", newline="\n")
    total_bytes = sum(path.stat().st_size for path in output.parent.glob(output.stem + "*.lua"))
    print(json.dumps({"output": str(output), "chunks": chunk_count, "groups": groups, "hero_names": len(hero_names), "bytes": total_bytes}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
